#!/usr/bin/env bash
# Install nginx web server listening on port 80 that returns a page that contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo ufw allow 80
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
