#!/usr/bin/env bash
# Install nginx web server listening on port 80 that returns a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "<h1>Hello World!</h1>" > /var/www/html/index.html
sudo service nginx start
