#!/usr/bin/env bash
#A script that Installs and configure HAproxy on the loadbalancer server.
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i '10 i ENABLED=1' /etc/default/haproxy
sudo sed -i '35 a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '40 a \\nbackend http_back\n\tbalance roundrobin\n\tserver 364991-web-01 54.237.119.232:80 check\n\tserver 364991-web-02 54.173.209.187:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
