#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

# update packages and install
sudo apt update
sudo apt install nginx

# creating a symbolic link for the default files
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# make sure to enable default
sudo nginx -s enable default
# start service
sudo service nginx start
