#!/usr/bin/env bash
	# this script displays bad luck for the 4th loop iteration
	# displays good luck for the 8th loop iteration
	# displays Best School for the other iterations

	n=0

	while [ $n -lt 10 ]
	do
	if [ $n -eq 3 ]
	then
	echo "bad luck"
	elif [ $n -eq 7 ]
	then
	echo "good luck"
	else
	echo "Best School"
	fi
	n=$((n + 1))
	done
