#!/usr/bin/env bash
#a Bash script that displays:
	#The content of the current directory
	#Where only the part of the name after the first dash is displayed

	for f_name in *
	do
		echo "$f_name" | cut -d "-" -f2-
	done
