#!/usr/bin/env bash
# installing a firewall and setting it up
# blocking all sockets except 22, 443, 80

sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
