#!/usr/bin/env bash
# nginx must be running as nginx user
sudo pkill apache2
sudo chmod 664 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo su nginx -c "service nginx start"
